#!/bin/bash
if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

PATH=/usr/local/bin:/usr/local/sbin:/sbin:/usr/sbin:/bin:/usr/bin:/usr/bin/X11

greenb() { echo $(tput bold)$(tput setaf 2)${1}$(tput sgr0); }
redb() { echo $(tput bold)$(tput setaf 1)${1}$(tput sgr0); }
yellowb() { echo $(tput bold)$(tput setaf 3)${1}$(tput sgr0); }

read -p "Old hostname: " oldHostname
read -p "Old domain: " oldDomain
read -p "New hostname: " newHostname
read -p "New domain: " newDomain

greenb "Changing the main hostname used by mailcow from ${oldHostname} to ${newHostname}"


sed -i "s/${oldHostname}.${oldDomain}/${newHostname}.${newDomain}/g" /etc/postfix/* 2> /dev/null
sed -i "s/${oldHostname}.${oldDomain}/${newHostname}.${newDomain}/g" /etc/dovecot/*
sed -i "s/${oldHostname}.${oldDomain};/${newHostname}.${newDomain};/g" /etc/nginx/sites-available/mailcow
sed -i "s/\"\${oldHostname}.${oldDomain}\"/\"${newHostname}.${newDomain}\"/g" /etc/apache2/sites-available/mailcow.conf
sed -i "s/${oldHostname}/${newHostname}/g" /var/www/mail/autoconfig.xml
sed -i "s/${oldHostname}.${oldDomain}/${newHostname}.${newDomain}/g" /var/www/zpush/backend/imap/config.php
sed -i "s/${oldHostname}.${oldDomain}/${newHostname}.${newDomain}/g" /var/www/mail/rc/config/config.inc.php

if [[ ! -z $(openssl x509 -issuer -in /etc/ssl/mail/mail.crt | grep ${oldHostname}.${oldDomain} ) ]]; then
	rm /etc/ssl/mail/* 2> /dev/null
	echo "$(textb [INFO]) - Generating 2048 bit DH parameters, this may take a while, please wait..."
	openssl dhparam -out /etc/ssl/mail/dhparams.pem 2048 2> /dev/null
	openssl req -new -newkey rsa:4096 -sha256 -days 1095 -nodes -x509 -subj "/CN=${newHostname}.${newDomain}" -keyout /etc/ssl/mail/mail.key  -out /etc/ssl/mail/mail.crt
	chmod 600 /etc/ssl/mail/mail.key
	cp /etc/ssl/mail/mail.crt /usr/local/share/ca-certificates/
	update-ca-certificates
else
	redb "You need to change your SSL-certificate"
fi

if [[ ! -f /etc/ssl/mail/dhparams.pem ]]; then
	echo "$(textb [INFO]) - Generating 2048 bit DH parameters, this may take a while, please wait..."
	rm /etc/ssl/mail/dhparams.pem
	openssl dhparam -out /etc/ssl/mail/dhparams.pem 2048 2> /dev/null
fi
